name: Go

on:
  push:
    branches:
      - main
      - release/*
      - devel/*
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15+
        stable: true
        token: ${{ github.token }}

    - name: Build
      run: go build -v ./goulist.go

    - name: Test
      run: go test -v ./goulist-test.go
  test:
    name: Test GoLang
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
      - uses: actions/checkout@v2
      - name: Test Go app on ${{ matrix.os }}
        uses: actions/setup-go@v2.1.3
        
      - name: go build, test, run
        run: |
          go build -v ./goulist.go
          go test -v ./goulist-test.go
          go run -v ./goulist.go
